/**
 * Configuration and Static Data for the Pathfinder App
 */

export const CLASSES = [
    { id: 'friend', n: 'Friend', e: '🌱', g: 'Grade 5', l: 'Level 1' },
    { id: 'companion', n: 'Companion', e: '🌿', g: 'Grade 6', l: 'Level 2' },
    { id: 'explorer', n: 'Explorer', e: '🧭', g: 'Grade 7', l: 'Level 3' },
    { id: 'ranger', n: 'Ranger', e: '⛺', g: 'Grade 8', l: 'Level 4' },
    { id: 'voyager', n: 'Voyager', e: '⚓', g: 'Grade 9', l: 'Level 5' },
    { id: 'guide', n: 'Guide', e: '🗺️', g: 'Grade 10', l: 'Level 6' },
    { id: 'masterguide', n: 'Master Guide', e: '🎓', g: 'Ages 16+', l: 'Leadership' },
];

export const AI_TIPS = {
    friend: [
        "As a Friend, try memorizing one Bible verse this week — it helps in every class level!",
        "Great pathfinders start with big hearts. Who can you encourage today?"
    ],
    companion: [
        "Working on your Companion honors? Remember: consistency beats speed every time!",
        "Companions build friendships that last. Reach out to a classmate you haven't talked to lately."
    ],
    explorer: [
        "Explorers lead the way! Have you started your personal fitness plan yet?",
        "You're in Grade 7 — this is the perfect year to start a devotional journal."
    ],
    ranger: [
        "Ranger class is when real leaders emerge. What honor are you currently working on?",
        "Don't forget — Camporee preparation counts toward your Ranger requirements!"
    ],
    voyager: [
        "Voyagers are almost at the top! Consider mentoring a Friend or Companion today.",
        "Your portfolio work now will make your Guide investiture smooth and strong."
    ],
    guide: [
        "As a Guide, you're an example for every younger Pathfinder. Lead with grace.",
        "Guide class teaches that real strength is in serving others. Look for ways to serve this week."
    ],
    masterguide: [
        "Master Guide candidates: have you scheduled your 12 leadership seminars?",
        "Remember your exit interview goal — document everything as you go, not at the end!"
    ],
};

export const DEVOTION_VERSES = [
    { v: "\"For God so loved the world that He gave His one and only Son...\"", r: 'John 3:16' },
    { v: "\"I can do all things through Christ who strengthens me.\"", r: 'Philippians 4:13' },
    { v: "\"Trust in the LORD with all your heart and lean not on your own understanding.\"", r: 'Proverbs 3:5' },
    { v: "\"The love of Christ compels us...\"", r: '2 Corinthians 5:14' },
    { v: "\"Be strong and courageous. Do not be afraid; do not be discouraged.\"", r: 'Joshua 1:9' },
    { v: "\"Let your light shine before others, that they may see your good deeds.\"", r: 'Matthew 5:16' },
    { v: "\"Train up a child in the way he should go; even when he is old he will not depart from it.\"", r: 'Proverbs 22:6' },
];

export const CLD_CLOUD = 'dq1kk9tkd';
export const CLD_PRESET = 'tyxio0qs';

export const HONORS_LIST = [
    { n: 'Knots', e: '🪢', c: 'Skills' }, { n: 'Camping', e: '🏕️', c: 'Outdoor' },
    { n: 'Stewardship', e: '💰', c: 'Life Skills' }, { n: 'Stars', e: '⭐', c: 'Nature' },
    { n: 'Trees', e: '🌳', c: 'Nature' }, { n: 'Birds', e: '🦜', c: 'Nature' },
    { n: 'First Aid', e: '🏥', c: 'Health' }, { n: 'Drawing', e: '🎨', c: 'Arts & Crafts' },
    { n: 'Swimming', e: '🏊', c: 'Aquatics' }, { n: 'Bible Study', e: '📖', c: 'Spiritual Dev.' },
    { n: 'Christian Storytelling', e: '📜', c: 'Outreach' }, { n: 'Adventist Heritage', e: '🕯️', c: 'Church' },
];

export const CLASS_REQUIREMENTS = {
    friend: [
        { cat: '🌱 Personal Growth', req: 'Memorize and recite the Pathfinder Pledge' },
        { cat: '🌱 Personal Growth', req: 'Memorize and recite the Pathfinder Law' },
        { cat: '🌱 Personal Growth', req: 'Know the Pathfinder Song by memory' },
        { cat: '🌱 Personal Growth', req: 'Make a personal daily schedule and follow it for 2 weeks' },
        { cat: '✍️ Spiritual Discovery', req: 'Memorize John 3:16 and Psalm 23:1' },
        { cat: '✍️ Spiritual Discovery', req: 'Have personal devotion daily for 2 weeks' },
        { cat: '✍️ Spiritual Discovery', req: 'Attend Sabbath School every week for 1 month' },
        { cat: '🤝 Serving Others', req: 'Complete one approved community service project' },
        { cat: '🤝 Serving Others', req: 'Do one kind act for someone outside your family each week for 4 weeks' },
        { cat: '👫 Making Friends', req: 'Learn the names of all Pathfinders in your unit' },
        { cat: '👫 Making Friends', req: 'Write a letter or card to someone who needs encouragement' },
        { cat: '💪 Health & Fitness', req: 'Know what NEWSTART stands for and explain each letter' },
        { cat: '💪 Health & Fitness', req: 'Exercise or play actively 3 times per week for 4 weeks' },
        { cat: '🌿 Nature Study', req: 'Collect and identify 10 different leaves, rocks, or insects' },
        { cat: '🌿 Nature Study', req: 'Spend time outdoors and write or draw 5 nature observations' },
        { cat: '⛺ Outdoor Living', req: 'Attend at least one Pathfinder outdoor event or nature walk' },
        { cat: '🏅 Honor Enrichment', req: 'Complete the Cooking honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete the Foot Care honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete one additional honor of your choice' },
    ],
    companion: [
        { cat: '🌱 Personal Growth', req: 'Recite Pledge and Law from memory without help' },
        { cat: '🌱 Personal Growth', req: 'Set a personal goal and work on it for 4 weeks' },
        { cat: '🌱 Personal Growth', req: 'Learn to manage your time — keep a daily planner for 2 weeks' },
        { cat: '✍️ Spiritual Discovery', req: 'Memorize 6 Bible verses including Proverbs 3:5-6' },
        { cat: '✍️ Spiritual Discovery', req: 'Keep a prayer journal for 4 weeks' },
        { cat: '✍️ Spiritual Discovery', req: 'Participate actively in Sabbath School each week' },
        { cat: '🤝 Serving Others', req: 'Complete 4 hours of community service' },
        { cat: '🤝 Serving Others', req: 'Help a family member with chores every day for 2 weeks' },
        { cat: '👫 Making Friends', req: 'Invite someone new to a Pathfinder meeting or church' },
        { cat: '👫 Making Friends', req: 'Resolve a disagreement with a friend or sibling peacefully' },
        { cat: '💪 Health & Fitness', req: 'Know all 8 NEWSTART principles and apply one for 4 weeks' },
        { cat: '💪 Health & Fitness', req: 'Exercise 3 times per week for 4 weeks — record results' },
        { cat: '🌿 Nature Study', req: 'Keep a nature journal with at least 8 entries' },
        { cat: '🌿 Nature Study', req: 'Identify 5 local trees or birds by name' },
        { cat: '⛺ Outdoor Living', req: 'Go on a nature walk and identify 10 things you observe' },
        { cat: '⛺ Outdoor Living', req: 'Learn how to set up and take down a tent' },
        { cat: '🏅 Honor Enrichment', req: 'Complete the Knot Tying honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete the Cooking honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete one craft honor of your choice' },
    ],
    explorer: [
        { cat: '🌱 Personal Growth', req: 'Explain the meaning of each clause in the Pledge and Law' },
        { cat: '🌱 Personal Growth', req: 'Complete a personal growth project approved by your director' },
        { cat: '🌱 Personal Growth', req: 'Learn a new skill and teach it to someone' },
        { cat: '✍️ Spiritual Discovery', req: 'Memorize 8 Bible verses; complete a 30-day reading plan' },
        { cat: '✍️ Spiritual Discovery', req: 'Lead an opening or closing prayer at a Pathfinder meeting' },
        { cat: '✍️ Spiritual Discovery', req: 'Study one Adventist belief and present it to your class' },
        { cat: '🤝 Serving Others', req: 'Complete 6 hours of community service' },
        { cat: '🤝 Serving Others', req: 'Share your faith story with one person outside your church' },
        { cat: '👫 Making Friends', req: 'Plan and carry out a social activity for your Pathfinder unit' },
        { cat: '👫 Making Friends', req: 'Write an encouraging letter to a missionary or church leader' },
        { cat: '💪 Health & Fitness', req: 'Apply two NEWSTART principles consistently for 6 weeks' },
        { cat: '💪 Health & Fitness', req: 'Complete a 4-week personal fitness program — record results' },
        { cat: '🌿 Nature Study', req: 'Identify 10 local birds, plants, or insects by sight' },
        { cat: '🌿 Nature Study', req: 'Complete a nature project and present it to your club' },
        { cat: '⛺ Outdoor Living', req: 'Learn basic map and compass skills' },
        { cat: '⛺ Outdoor Living', req: 'Participate in a Pathfinder camping trip' },
        { cat: '🏅 Honor Enrichment', req: 'Complete the First Aid honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete the Camping Skills 1 honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete one household arts honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete one nature honor' },
    ],
    ranger: [
        { cat: '🌱 Personal Growth', req: 'Teach the Pledge and Law to a younger Pathfinder' },
        { cat: '🌱 Personal Growth', req: 'Complete a leadership training activity' },
        { cat: '🌱 Personal Growth', req: 'Lead one Pathfinder meeting activity or worship' },
        { cat: '✍️ Spiritual Discovery', req: 'Memorize 10 Bible verses; read Steps to Christ' },
        { cat: '✍️ Spiritual Discovery', req: 'Have daily devotions for 6 weeks; share one with your class' },
        { cat: '✍️ Spiritual Discovery', req: 'Know and explain all 28 Fundamental Beliefs (overview)' },
        { cat: '✍️ Spiritual Discovery', req: 'Give a Bible study or share your personal testimony' },
        { cat: '🤝 Serving Others', req: 'Complete 10 hours of community service' },
        { cat: '🤝 Serving Others', req: 'Organize a service project for your community' },
        { cat: '👫 Making Friends', req: 'Mentor or befriend a new or younger Pathfinder' },
        { cat: '👫 Making Friends', req: 'Participate in a Pathfinder outreach activity' },
        { cat: '💪 Health & Fitness', req: 'Complete a 6-week personal fitness program — record results' },
        { cat: '💪 Health & Fitness', req: 'Know advanced first aid and CPR basics' },
        { cat: '🌿 Nature Study', req: 'Complete a nature study project and present to club' },
        { cat: '🌿 Nature Study', req: 'Identify 15 local species (plants, birds, or animals)' },
        { cat: '⛺ Outdoor Living', req: 'Participate in Camporee and Pathfinder Fair' },
        { cat: '⛺ Outdoor Living', req: 'Learn outdoor cooking and prepare a meal outdoors' },
        { cat: '🏅 Honor Enrichment', req: 'Complete Camping Skills 2 honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete one aquatics honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete one spiritual development honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete two additional honors of your choice' },
    ],
    voyager: [
        { cat: '🌱 Personal Growth', req: 'Teach Pledge and Law to a younger Pathfinder' },
        { cat: '🌱 Personal Growth', req: 'Mentor a younger Pathfinder for at least 2 months' },
        { cat: '🌱 Personal Growth', req: 'Complete a personal growth portfolio entry' },
        { cat: '✍️ Spiritual Discovery', req: 'Memorize 12 Bible verses; complete 60-day devotional plan' },
        { cat: '✍️ Spiritual Discovery', req: 'Know all 28 Fundamental Beliefs in depth' },
        { cat: '✍️ Spiritual Discovery', req: 'Lead family or group worship at least twice' },
        { cat: '✍️ Spiritual Discovery', req: 'Complete a personal evangelism project' },
        { cat: '🤝 Serving Others', req: 'Complete 14 hours of community service' },
        { cat: '🤝 Serving Others', req: 'Lead a community outreach activity' },
        { cat: '👫 Making Friends', req: 'Plan a social or outreach event for your unit or community' },
        { cat: '👫 Making Friends', req: 'Write and send 3 encouraging messages to people in need' },
        { cat: '💪 Health & Fitness', req: 'Complete an 8-week fitness program — set and achieve a goal' },
        { cat: '💪 Health & Fitness', req: 'Complete First Aid with CPR certification' },
        { cat: '🌿 Nature Study', req: 'Complete an advanced nature study and present findings' },
        { cat: '🌿 Nature Study', req: 'Identify 20 local species across different categories' },
        { cat: '⛺ Outdoor Living', req: 'Attend Division or Union Camporee' },
        { cat: '⛺ Outdoor Living', req: 'Demonstrate advanced camping and outdoor survival skills' },
        { cat: '🏅 Honor Enrichment', req: 'Complete Camping Skills 3 honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete one health honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete one outreach or missionary honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete three additional honors of your choice' },
    ],
    guide: [
        { cat: '🌱 Personal Growth', req: 'Be able to train others in the Pledge and Law' },
        { cat: '🌱 Personal Growth', req: 'Lead a Pathfinder class for one full month' },
        { cat: '🌱 Personal Growth', req: 'Prepare a portfolio of all Guide class requirements' },
        { cat: '✍️ Spiritual Discovery', req: 'Memorize 15 Bible verses; complete a Bible marking series' },
        { cat: '✍️ Spiritual Discovery', req: 'Study and present one Fundamental Belief to your group' },
        { cat: '✍️ Spiritual Discovery', req: 'Conduct a week of prayer for your class' },
        { cat: '✍️ Spiritual Discovery', req: 'Conduct Bible studies with someone outside the church' },
        { cat: '🤝 Serving Others', req: 'Complete 20 hours of community service' },
        { cat: '🤝 Serving Others', req: 'Teach a skill or honor to other Pathfinders' },
        { cat: '🤝 Serving Others', req: 'Organize and lead an evangelism project' },
        { cat: '👫 Making Friends', req: 'Plan and carry out a club-wide social or outreach event' },
        { cat: '👫 Making Friends', req: 'Build a mentoring relationship with a younger Pathfinder' },
        { cat: '💪 Health & Fitness', req: 'Complete a 12-week fitness program — document all results' },
        { cat: '💪 Health & Fitness', req: 'Complete Emergency Response honor' },
        { cat: '🌿 Nature Study', req: 'Complete a major nature research project' },
        { cat: '🌿 Nature Study', req: 'Identify 25 local species across all major categories' },
        { cat: '⛺ Outdoor Living', req: 'Attend Conference or Union Camporee' },
        { cat: '⛺ Outdoor Living', req: 'Complete Camping Skills — Master honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete one outreach honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete five additional honors of your choice' },
    ],
    masterguide: [
        { cat: '✍️ Spiritual Discovery', req: 'Complete all Spiritual Growth curriculum areas' },
        { cat: '🌱 Personal Growth', req: 'Read Education by Ellen G. White' },
        { cat: '🌱 Personal Growth', req: 'Complete child development seminar' },
        { cat: '🌱 Personal Growth', req: 'Write a 2-page temperament analysis paper' },
        { cat: '🤝 Serving Others', req: 'Supervise a Pathfinder class for one full year' },
        { cat: '🤝 Serving Others', req: 'Conduct exit interview with Conference Youth Director' },
        { cat: '👫 Making Friends', req: 'Complete 12 leadership seminars (90 min each)' },
        { cat: '💪 Health & Fitness', req: 'Complete AY Silver or Gold Award' },
        { cat: '💪 Health & Fitness', req: 'Complete personal fitness documentation' },
        { cat: '⛺ Outdoor Living', req: 'Complete Camping Skills honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete Christian Storytelling honor' },
        { cat: '🏅 Honor Enrichment', req: 'Complete First Aid Instructor honor' },
        { cat: '🌱 Personal Growth', req: 'Attend 75% of all club staff meetings' },
        { cat: '🌱 Personal Growth', req: 'Submit complete Master Guide portfolio' },
    ],
};

export const MG = [
    { a: 'I. Spiritual Growth', e: '✍️', items: ['Read Steps to Christ', 'Devotional journal 4 weeks', 'Bible studies on 28 Beliefs', 'Encounter Series I'] },
    { a: 'II. New Skills', e: '🛠️', items: ['Camping Skills', 'Christian Storytelling Honor', 'First Aid Certificate', '2 additional AY Honors'] },
    { a: 'III. Leadership Dev.', e: '🎓', items: ['3 creative worships', 'Conference leadership event', 'Teach 3 Adventurer Awards', 'Field trip leadership'] },
    { a: 'IV. Personal Growth', e: '📖', items: ['Read "Education" (E. White)', 'Child development seminar', '2-page temperament paper', '12 leadership seminars'] },
    { a: 'V. Fitness Lifestyle', e: '🏃', items: ['AY Silver or Gold Award', 'Personal fitness plan', 'Physical fitness documentation'] },
    { a: 'VI. Portfolio & Service', e: '📂', items: ['Document all work', '75% staff meeting attendance', 'Supervise Pathfinder class 1 year', 'Exit interview'] },
];

export const CLASS_HONORS = {
    friend: [
        { n: 'Apiculture (Bees)', cat: 'Nature', e: '🐝' },
        { n: 'Bird Study', cat: 'Nature', e: '🐦' },
        { n: 'Cooking', cat: 'Household Arts', e: '🍳' },
        { n: 'First Aid — Basic', cat: 'Health', e: '🏥' },
        { n: 'Gardening', cat: 'Nature', e: '🌱' },
        { n: 'Knot Tying', cat: 'Outdoor Industries', e: '🪢' },
        { n: 'Sewing', cat: 'Household Arts', e: '🧵' },
        { n: 'Drawing', cat: 'Arts & Crafts', e: '🎨' },
    ],
    companion: [
        { n: 'Camping', cat: 'Recreation', e: '⛺' },
        { n: 'Cooking', cat: 'Household Arts', e: '🍳' },
        { n: 'First Aid', cat: 'Health', e: '🏥' },
        { n: 'Map & Compass', cat: 'Recreation', e: '🧭' },
        { n: 'Nature Study', cat: 'Nature', e: '🌿' },
        { n: 'Swimming — Beginner', cat: 'Aquatics', e: '🏊' },
        { n: 'Bible Marking', cat: 'Spiritual Dev.', e: '📖' },
        { n: 'Photography', cat: 'Arts & Crafts', e: '📸' },
    ],
    explorer: [
        { n: 'Camping Skills I', cat: 'Recreation', e: '⛺' },
        { n: 'First Aid', cat: 'Health', e: '🏥' },
        { n: 'Hiking', cat: 'Recreation', e: '🥾' },
        { n: 'Map & Compass', cat: 'Recreation', e: '🧭' },
        { n: 'Swimming', cat: 'Aquatics', e: '🏊' },
        { n: 'Christian Storytelling', cat: 'Spiritual Dev.', e: '📜' },
        { n: 'Cooking — Advanced', cat: 'Household Arts', e: '🍳' },
        { n: 'Nature Drawing', cat: 'Arts & Crafts', e: '🎨' },
    ],
    ranger: [
        { n: 'Camping Skills II', cat: 'Recreation', e: '⛺' },
        { n: 'First Aid — Advanced', cat: 'Health', e: '🏥' },
        { n: 'Orienteering', cat: 'Recreation', e: '🧭' },
        { n: 'Swimming — Intermediate', cat: 'Aquatics', e: '🏊' },
        { n: 'Bible Prophecy', cat: 'Spiritual Dev.', e: '📖' },
        { n: 'Cooking — Camp', cat: 'Household Arts', e: '🔥' },
        { n: 'Music', cat: 'Arts & Crafts', e: '🎵' },
        { n: 'Leadership', cat: 'Spiritual Dev.', e: '🎖️' },
    ],
    voyager: [
        { n: 'Camping Skills III', cat: 'Recreation', e: '⛺' },
        { n: 'First Aid — CPR', cat: 'Health', e: '🫁' },
        { n: 'Life Saving', cat: 'Aquatics', e: '🛟' },
        { n: 'Christian Citizenship', cat: 'Spiritual Dev.', e: '✍️' },
        { n: 'Heritage', cat: 'Spiritual Dev.', e: '🕯️' },
        { n: 'Cooking — Nutrition', cat: 'Household Arts', e: '🥗' },
        { n: 'Photography', cat: 'Arts & Crafts', e: '📸' },
        { n: 'Public Speaking', cat: 'Spiritual Dev.', e: '🎤' },
    ],
    guide: [
        { n: 'Camping Skills — Master', cat: 'Recreation', e: '⛺' },
        { n: 'Emergency Response', cat: 'Health', e: '🚑' },
        { n: 'Water Safety', cat: 'Aquatics', e: '🛟' },
        { n: 'Teaching Skills', cat: 'Spiritual Dev.', e: '👩‍🏫' },
        { n: 'Adventist Heritage', cat: 'Spiritual Dev.', e: '🕯️' },
        { n: 'Cooking — Vegetarian', cat: 'Household Arts', e: '🥬' },
        { n: 'Community Service', cat: 'Spiritual Dev.', e: '🤝' },
        { n: 'Mentorship', cat: 'Spiritual Dev.', e: '🎓' },
    ],
    masterguide: [
        { n: 'Christian Storytelling', cat: 'Outreach', e: '📜' },
        { n: 'Camping Skills', cat: 'Recreation', e: '⛺' },
        { n: 'First Aid — Instructor', cat: 'Health', e: '🏥' },
        { n: 'Teaching Methods', cat: 'Leadership', e: '👩‍🏫' },
        { n: 'Youth Leadership', cat: 'Leadership', e: '🎖️' },
        { n: 'Community Evangelism', cat: 'Outreach', e: '✍️' },
    ],
};
